apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: credit-team-all
  description: All employees part of credit team
spec:
  targets:
    - ./team/org.yaml
    - ./team/3p.yaml
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: credit
spec:
  owner: credit-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CreditOCSService
  description: OCSService APIs
  labels:
    example.com/custom: custom_label_value
  annotations:
    jenkins.io/job-full-name: Creditrating/CIR/OCSService/Int/build-image
    jira/project-key: CRD
    backstage.io/code-coverage: scm-only
    backstage.io/techdocs-ref: github:https://github.com/venkatasandeep506/backstage-test-public-repo
    # jira/component: <example-component> # optional, you might skip this value to fetch data for all components
    # jira/token-type: Bearer # optional, used for Activity stream feed. If you are using Basic auth you can skip this.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - gradle
  links:
    - url: https://goyubi.atlassian.net/wiki/spaces/CRED/overview
      title: OCS Confluence
      icon: dashboard
      type: ocs-confluence-dashboard
spec:
  type: service
  owner: venkatasandeep.godavarthi@go-yubi.com
  lifecycle: production
  system: credit
  providesApis:
    - test-api
    - flex-api
  consumesApis:
    - 3p-apis
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-api
spec:
  type: grpc
  lifecycle: experimental
  owner: testapi@go-yubi.com
  system: credit
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: flex-api
spec:
  type: openapi
  lifecycle: production
  owner: flex-group
  system: credit
  definition:
    $text: https://cir-ocs-qa.go-yubi.in/v2/api-docs
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: 3p-apis
spec:
  type: openapi
  lifecycle: production
  owner: 3p-group
  definition:
    $text: https://3p-cir-qa.go-yubi.in/v2/api-docs
