apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-application1
  description: Test Application1
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: testuser@go-yubi.com
  lifecycle: experimental
