apiVersion: backstage.io/v1alpha
kind: Component
metadata:
  name: test-application-name
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: testuser@go-yubi.com
  lifecycle: experimental
