---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platform-auth-service
  description: Platform Auth Service
  tags:
    - jenkins
    - jira 
    - postman
#  title: Platform Authorization Service
  annotations:
#    jenkins.io/job-full-name: Creditrating/CIR/OCSService/Int/build-image
    jira/project-key: CP
    backstage.io/code-coverage: scm-only
    backstage.io/techdocs-ref: dir:.
    newrelic.com/dashboard-guid: Mjg0NjIxOXxWSVp8REFTSEJPQVJEfGRhOjI3NzQ5MjA
#    documentation: "https://documenter.getpostman.com/view/15548094/"
#    environment: "production"
  links:
    - url: https://goyubi.atlassian.net/jira/software/c/projects/CP/boards/53?quickFilter=186
      title: Jira Dashboard
      icon: dashboard
      type: jira-dashboard
    - url: https://jenkins.dso.credavenue.io/job/Platforms/job/UserAuth/job/Api/job/Prd/
      title: Jenkins Dashboard
      icon: dashboard
      type: jenkins-dashboard
    # - url: https://documenter.getpostman.com/view/15548094/TzXwFe7Q
    #   title: APIs/Swagger link
    #   icon: dashboard
    #   type: postman-dashboard
    # - url: https://documenter.getpostman.com/view/15548094/TzY7dtsP
    #   title: User Service Apis
    #   icon: dashboard
    #   type: postman-dashboard
    # - url: https://documenter.getpostman.com/view/15548094/2s847PKA4L
    #   title: CNS
    #   icon: dashboard
    #   type: postman-dashboard
spec:
  type: service
  lifecycle: production
  owner: group:common-platform
#  system: platform
  consumesApis:
    - auth0-apis
    - cns-apis
#  dependsOn:
#    - component:CreditOCSService
#    - component:Pools
#    - component:Co-lending
#    - component:SCF
#    - component:Loans
#    - component:Invest
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth0-apis
spec:
  type: openapi
  lifecycle: production
#  owner: thirdparty
#  definition:
#    $text: https://3p-cir-qa.go-yubi.in/v2/api-docs
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cns-apis
spec:
  type: openapi
  lifecycle: production
#  owner: thirdparty
#  definition:
#    $text: https://3p-cir-qa.go-yubi.in/v2/api-docs
---
