apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: 3p-group
  description: Team 3P
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: 3p@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Abhishek
spec:
  profile:
    # Intentional no displayName for testing
    displayName: Abhishek Goel
    email: abishek@go-yubi.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [3p-group]